string(APPEND FFLAGS " -fp-model consistent -fimf-use-svml -qno-openmp-simd")
string(APPEND CXXFLAGS " -fp-model consistent")
if (NOT DEBUG)
  string(APPEND FFLAGS " -qno-opt-dynamic-align")
endif()
string(APPEND SLIBS " -mkl -lpthread")
